spring.application.name=hms
server.port=7765

# Database connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration-ms=86400000

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Groq
groq.api.key=${GROQ_API_KEY}
groq.model=llama-3.3-70b-versatile