// useLookup.js — provides dropdown values for all lookup types used in the HMS forms
// All values are statically defined (no backend lookup API exists)

const LOOKUP_DATA = {
  GENDER: [
    { value: "Male", label: "Male" },
    { value: "Female", label: "Female" },
    { value: "Other", label: "Other" },
  ],
  BLOOD_GROUP: [
    { value: "A+", label: "A+" },
    { value: "A-", label: "A-" },
    { value: "B+", label: "B+" },
    { value: "B-", label: "B-" },
    { value: "AB+", label: "AB+" },
    { value: "AB-", label: "AB-" },
    { value: "O+", label: "O+" },
    { value: "O-", label: "O-" },
  ],
  PATIENT_TYPE: [
    { value: "OPD", label: "OPD (Out-Patient)" },
    { value: "IPD", label: "IPD (In-Patient)" },
    { value: "Emergency", label: "Emergency" },
  ],
  ACTIVE_STATUS: [
    { value: "ACTIVE", label: "Active" },
    { value: "INACTIVE", label: "Inactive" },
  ],
  SPECIALIZATION: [
    { value: "General Medicine", label: "General Medicine" },
    { value: "Cardiology", label: "Cardiology" },
    { value: "Orthopedics", label: "Orthopedics" },
    { value: "Pediatrics", label: "Pediatrics" },
    { value: "Gynecology", label: "Gynecology" },
    { value: "Neurology", label: "Neurology" },
    { value: "Oncology", label: "Oncology" },
    { value: "Dermatology", label: "Dermatology" },
    { value: "Ophthalmology", label: "Ophthalmology" },
    { value: "ENT", label: "ENT" },
    { value: "Psychiatry", label: "Psychiatry" },
    { value: "Radiology", label: "Radiology" },
    { value: "Anesthesiology", label: "Anesthesiology" },
    { value: "Surgery", label: "Surgery" },
    { value: "Urology", label: "Urology" },
    { value: "Nephrology", label: "Nephrology" },
    { value: "Gastroenterology", label: "Gastroenterology" },
    { value: "Pulmonology", label: "Pulmonology" },
    { value: "Endocrinology", label: "Endocrinology" },
    { value: "Emergency Medicine", label: "Emergency Medicine" },
  ],
  STAFF_STATUS: [
    { value: "ACTIVE", label: "Active" },
    { value: "INACTIVE", label: "Inactive" },
    { value: "ON_LEAVE", label: "On Leave" },
    { value: "TERMINATED", label: "Terminated" },
  ],
  STAFF_ROLE: [
    { value: "Nurse", label: "Nurse" },
    { value: "Head Nurse", label: "Head Nurse" },
    { value: "Lab Technician", label: "Lab Technician" },
    { value: "Pharmacist", label: "Pharmacist" },
    { value: "Receptionist", label: "Receptionist" },
    { value: "Admin Staff", label: "Admin Staff" },
    { value: "Ward Boy", label: "Ward Boy" },
    { value: "Housekeeping", label: "Housekeeping" },
    { value: "Security", label: "Security" },
    { value: "Ambulance Driver", label: "Ambulance Driver" },
    { value: "Accountant", label: "Accountant" },
    { value: "IT Support", label: "IT Support" },
  ],
  SHIFT_TYPE: [
    { value: "MORNING", label: "Morning (6AM-2PM)" },
    { value: "AFTERNOON", label: "Afternoon (2PM-10PM)" },
    { value: "NIGHT", label: "Night (10PM-6AM)" },
    { value: "ROTATING", label: "Rotating Shift" },
    { value: "GENERAL", label: "General (9AM-5PM)" },
  ],
  WARD_TYPE: [
    { value: "General", label: "General Ward" },
    { value: "ICU", label: "ICU" },
    { value: "NICU", label: "NICU" },
    { value: "PICU", label: "PICU" },
    { value: "Private", label: "Private Room" },
    { value: "Semi-Private", label: "Semi-Private Room" },
    { value: "Emergency", label: "Emergency Ward" },
    { value: "Post-Op", label: "Post-Operative" },
    { value: "Maternity", label: "Maternity" },
    { value: "Psychiatric", label: "Psychiatric" },
    { value: "Isolation", label: "Isolation" },
  ],
  OPERATIONAL_STATUS: [
    { value: "ACTIVE", label: "Active" },
    { value: "INACTIVE", label: "Inactive" },
    { value: "UNDER_MAINTENANCE", label: "Under Maintenance" },
  ],
  CONSULTATION_TYPE: [
    { value: "OPD", label: "OPD" },
    { value: "IPD", label: "IPD" },
    { value: "Emergency", label: "Emergency" },
    { value: "Follow-up", label: "Follow-up" },
    { value: "Teleconsultation", label: "Teleconsultation" },
  ],
  CONSULTATION_STATUS: [
    { value: "SCHEDULED", label: "Scheduled" },
    { value: "IN_PROGRESS", label: "In Progress" },
    { value: "COMPLETED", label: "Completed" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "NO_SHOW", label: "No Show" },
  ],
  ADMISSION_TYPE: [
    { value: "PLANNED", label: "Planned" },
    { value: "EMERGENCY", label: "Emergency" },
    { value: "TRANSFER", label: "Transfer" },
    { value: "DAY_CARE", label: "Day Care" },
  ],
  PRIORITY: [
    { value: "CRITICAL", label: "Critical" },
    { value: "HIGH", label: "High" },
    { value: "MEDIUM", label: "Medium" },
    { value: "LOW", label: "Low" },
    { value: "NORMAL", label: "Normal" },
  ],
  SEVERITY_LEVEL: [
    { value: "CRITICAL", label: "Critical (Life-threatening)" },
    { value: "HIGH", label: "High (Urgent)" },
    { value: "MODERATE", label: "Moderate" },
    { value: "LOW", label: "Low (Non-urgent)" },
  ],
  EMERGENCY_STATUS: [
    { value: "ACTIVE", label: "Active" },
    { value: "STABILIZED", label: "Stabilized" },
    { value: "TRANSFERRED", label: "Transferred" },
    { value: "ADMITTED", label: "Admitted" },
    { value: "DISCHARGED", label: "Discharged" },
    { value: "DECEASED", label: "Deceased" },
  ],
  TRANSPORT_MODE: [
    { value: "AMBULANCE", label: "Ambulance" },
    { value: "SELF", label: "Self / Walk-in" },
    { value: "PRIVATE_VEHICLE", label: "Private Vehicle" },
    { value: "POLICE", label: "Police" },
    { value: "REFERRED", label: "Referred" },
  ],
  TRIAGE_CATEGORY: [
    { value: "RED", label: "Red — Immediate" },
    { value: "ORANGE", label: "Orange — Very Urgent" },
    { value: "YELLOW", label: "Yellow — Urgent" },
    { value: "GREEN", label: "Green — Standard" },
    { value: "BLUE", label: "Blue — Non-urgent" },
  ],
  ANESTHESIA_TYPE: [
    { value: "GENERAL", label: "General Anesthesia" },
    { value: "SPINAL", label: "Spinal" },
    { value: "EPIDURAL", label: "Epidural" },
    { value: "LOCAL", label: "Local Anesthesia" },
    { value: "REGIONAL", label: "Regional Block" },
    { value: "SEDATION", label: "Sedation" },
  ],
  OT_STATUS: [
    { value: "SCHEDULED", label: "Scheduled" },
    { value: "IN_PROGRESS", label: "In Progress" },
    { value: "COMPLETED", label: "Completed" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "POSTPONED", label: "Postponed" },
  ],
  MEDICINE_CATEGORY: [
    { value: "Tablet", label: "Tablet" },
    { value: "Capsule", label: "Capsule" },
    { value: "Syrup", label: "Syrup" },
    { value: "Injection", label: "Injection" },
    { value: "Ointment", label: "Ointment" },
    { value: "Drops", label: "Drops" },
    { value: "Inhaler", label: "Inhaler" },
    { value: "Powder", label: "Powder" },
    { value: "Suspension", label: "Suspension" },
    { value: "IV Fluid", label: "IV Fluid" },
    { value: "Vaccine", label: "Vaccine" },
    { value: "Surgical Supply", label: "Surgical Supply" },
  ],
  LAB_TEST_CATEGORY: [
    { value: "Hematology", label: "Hematology" },
    { value: "Biochemistry", label: "Biochemistry" },
    { value: "Microbiology", label: "Microbiology" },
    { value: "Serology", label: "Serology" },
    { value: "Pathology", label: "Pathology" },
    { value: "Radiology", label: "Radiology" },
    { value: "Endocrinology", label: "Endocrinology" },
    { value: "Immunology", label: "Immunology" },
    { value: "Urine Analysis", label: "Urine Analysis" },
    { value: "ECG", label: "ECG / EEG" },
    { value: "Ultrasound", label: "Ultrasound" },
    { value: "CT Scan", label: "CT Scan" },
    { value: "MRI", label: "MRI" },
  ],
  SAMPLE_STATUS: [
    { value: "PENDING_COLLECTION", label: "Pending Collection" },
    { value: "COLLECTED", label: "Collected" },
    { value: "PROCESSING", label: "Processing" },
    { value: "COMPLETED", label: "Completed" },
    { value: "REJECTED", label: "Rejected" },
  ],
  TEST_STATUS: [
    { value: "ORDERED", label: "Ordered" },
    { value: "IN_PROGRESS", label: "In Progress" },
    { value: "COMPLETED", label: "Completed" },
    { value: "CANCELLED", label: "Cancelled" },
  ],
  RESULT_STATUS: [
    { value: "NORMAL", label: "Normal" },
    { value: "ABNORMAL", label: "Abnormal" },
    { value: "CRITICAL", label: "Critical" },
    { value: "PENDING", label: "Pending" },
  ],
  PAYMENT_STATUS: [
    { value: "PENDING", label: "Pending" },
    { value: "PAID", label: "Paid" },
    { value: "PARTIAL", label: "Partial" },
    { value: "OVERDUE", label: "Overdue" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "REFUNDED", label: "Refunded" },
  ],
  PAYMENT_MODE: [
    { value: "CASH", label: "Cash" },
    { value: "UPI", label: "UPI" },
    { value: "CARD", label: "Credit/Debit Card" },
    { value: "NETBANKING", label: "Net Banking" },
    { value: "CHEQUE", label: "Cheque" },
    { value: "INSURANCE", label: "Insurance" },
    { value: "DD", label: "Demand Draft" },
  ],
  INSURANCE_CLAIM_STATUS: [
    { value: "PENDING", label: "Pending" },
    { value: "SUBMITTED", label: "Submitted" },
    { value: "UNDER_REVIEW", label: "Under Review" },
    { value: "APPROVED", label: "Approved" },
    { value: "PARTIALLY_APPROVED", label: "Partially Approved" },
    { value: "REJECTED", label: "Rejected" },
    { value: "SETTLED", label: "Settled" },
  ],
  DISCHARGE_CONDITION: [
    { value: "STABLE", label: "Stable" },
    { value: "IMPROVED", label: "Improved" },
    { value: "CRITICAL", label: "Critical" },
    { value: "AGAINST_ADVICE", label: "Against Medical Advice (LAMA)" },
    { value: "REFERRED", label: "Referred" },
    { value: "EXPIRED", label: "Expired" },
  ],
  DISCHARGE_TYPE: [
    { value: "REGULAR", label: "Regular Discharge" },
    { value: "LAMA", label: "LAMA (Left Against Medical Advice)" },
    { value: "REFER", label: "Referred to Another Facility" },
    { value: "DEATH", label: "Death" },
    { value: "DAY_CARE", label: "Day Care Discharge" },
  ],
  DOCUMENT_STATUS: [
    { value: "DRAFT", label: "Draft" },
    { value: "FINALIZED", label: "Finalized" },
    { value: "CANCELLED", label: "Cancelled" },
  ],
  PRESCRIPTION_TYPE: [
    { value: "OPD", label: "OPD Prescription" },
    { value: "IPD", label: "IPD Prescription" },
    { value: "EMERGENCY", label: "Emergency" },
    { value: "DISCHARGE", label: "Discharge Prescription" },
  ],
  PRESCRIPTION_STATUS: [
    { value: "ACTIVE", label: "Active" },
    { value: "COMPLETED", label: "Completed" },
    { value: "CANCELLED", label: "Cancelled" },
    { value: "DISPENSED", label: "Dispensed" },
  ],
  NURSING_NOTE_TYPE: [
    { value: "ROUTINE", label: "Routine Note" },
    { value: "HANDOVER", label: "Shift Handover" },
    { value: "VITALS", label: "Vitals Monitoring" },
    { value: "MEDICATION", label: "Medication Administration" },
    { value: "PROCEDURE", label: "Procedure Note" },
    { value: "INCIDENT", label: "Incident Report" },
  ],
  ADVANCE_TYPE: [
    { value: "ADMISSION_ADVANCE", label: "Admission Advance" },
    { value: "SURGERY_ADVANCE", label: "Surgery Advance" },
    { value: "GENERAL", label: "General Advance" },
  ],
  ADVANCE_STATUS: [
    { value: "PENDING", label: "Pending" },
    { value: "ADJUSTED", label: "Adjusted" },
    { value: "REFUNDED", label: "Refunded" },
    { value: "CANCELLED", label: "Cancelled" },
  ],
  HOSPITAL_TYPE: [
    { value: "GOVERNMENT", label: "Government" },
    { value: "PRIVATE", label: "Private" },
    { value: "TRUST", label: "Trust / NGO" },
    { value: "AUTONOMOUS", label: "Autonomous" },
    { value: "MULTI_SPECIALTY", label: "Multi-Specialty" },
    { value: "SUPER_SPECIALTY", label: "Super-Specialty" },
    { value: "CLINIC", label: "Clinic" },
    { value: "NURSING_HOME", label: "Nursing Home" },
    { value: "AYURVEDIC", label: "Ayurvedic / AYUSH" },
    { value: "DENTAL", label: "Dental" },
  ],
  YES_NO: [
    { value: true, label: "Yes" },
    { value: false, label: "No" },
  ],
};

export function useLookup(_unusedCodes = []) {
  const getValues = (code) => LOOKUP_DATA[code] || [];
  return { getValues };
}
